{
 "title": "Storj-Exporter",
 "tags": [
  "storj",
  "docker",
  "prometheus",
  "exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node:",
    "query": "label_values(storj_nodeID_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Combined Storj-exporter summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Earnings total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(storj_sat_summary{type=\"storageSummary\"}) / (days_in_month() * 24) * 1.5  / 1000^4) + (sum(storj_sat_month_egress) / 1000^4 * 20)"
    }
   ]
  },
  {
   "title": "Storage total",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum(storj_total_diskspace{type=\"used\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Net IO/sum monthly",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(storj_sat_month_egress) by(instance)",
     "legendFormat": "{{instance}} Out"
    },
    {
     "expr": "- sum(storj_sat_month_ingress) by(instance)",
     "legendFormat": "{{instance}} In"
    }
   ]
  },
  {
   "title": "Uptime avg score (* 100)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg(storj_sat_uptime{type=\"score\"}) by(instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Net IO/sum per node monthly",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Net IO rate" }
   ],
   "targets": [
    {
     "expr": "sum(storj_sat_month_egress) by(instance)",
     "legendFormat": "SumOut {{instance}}"
    },
    {
     "expr": "sum(storj_sat_month_ingress) by(instance)",
     "legendFormat": "SumIn {{instance}}"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress[5m])) by(instance) * 8",
     "legendFormat": "RateOut {{instance}}"
    },
    {
     "expr": "sum(rate(storj_sat_month_ingress[5m])) by(instance) * 8",
     "legendFormat": "RateIn {{instance}}"
    }
   ]
  },
  {
   "title": "Nodes online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(storj_nodeID_info)", "legendFormat": "Node sum" }
   ]
  },
  {
   "title": "Storage total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(storj_total_diskspace{type=\"used\"})",
     "legendFormat": "Node sum"
    }
   ]
  },
  {
   "title": "Audit avg score (* 100)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "avg(storj_sat_audit{type=~\"score|auditScore\"}) by(instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage In/Total per node monthly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes", "label": "Storage IO rate" }
   ],
   "targets": [
    {
     "expr": "sum(storj_total_diskspace{type=\"used\"}) by(instance)",
     "legendFormat": "DiskSum {{instance}}"
    },
    {
     "expr": "sum(delta(storj_total_diskspace{type=\"used\"}[5m])) by(instance) * 8 / 300",
     "legendFormat": "DiskRate {{instance}}"
    }
   ]
  },
  {
   "title": "Net Out total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(storj_sat_month_egress)", "legendFormat": "Node sum" }
   ]
  },
  {
   "title": "Net In total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(storj_sat_month_ingress)", "legendFormat": "Node sum" }
   ]
  },
  {
   "title": "Audit/Repair IO/sum per node monthly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes", "label": "Net IO rate" }
   ],
   "targets": [
    {
     "expr": "sum(storj_sat_month_egress{type!=\"usage\"}) by(type,instance)",
     "legendFormat": "SumOut-{{type}}-{{instance}}"
    },
    {
     "expr": "sum(storj_sat_month_ingress{type!=\"usage\"}) by(type,instance)",
     "legendFormat": "SumIn-{{type}}-{{instance}}"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress{type!=\"usage\"}[5m])) by(type,instance) * 8",
     "legendFormat": "RateOut-{{type}}-{{instance}}"
    },
    {
     "expr": "sum(rate(storj_sat_month_ingress{type!=\"usage\"}[5m])) by(type,instance) * 8",
     "legendFormat": "RateIn-{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Up to date",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "storj_upToDate_info", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Storj-exporter $node details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "node" },
  {
   "title": "$node Earnings",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(storj_sat_summary{type=\"storageSummary\",instance=~\"$node.*\"}) / (days_in_month() * 24) * 1.5  / 1000^4) + (sum(storj_sat_month_egress{instance=~\"$node.*\"}) / 1000^4 * 20)"
    }
   ]
  },
  {
   "title": "$node Disk used",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 21 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "storj_total_diskspace{type=\"used\",instance=~\"$node.*\"}"
    }
   ]
  },
  {
   "title": "$node Uptime score (* 100)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "storj_sat_uptime{instance=~\"$node.*\",type=\"score\"} * 100",
     "legendFormat": "{{satellite}}"
    }
   ]
  },
  {
   "title": "$node Audit score (* 100)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 21 },
   "targets": [
    {
     "expr": "storj_sat_audit{type=~\"score|auditScore\",instance=~\"$node.*\"} * 100",
     "legendFormat": "{{satellite}}"
    }
   ]
  },
  {
   "title": "$node Net IO/sum",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes", "label": "Net IO rate" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_egress{instance=~\"$node.*\"}[5m])) * 8",
     "legendFormat": "RateOut {{instance}}"
    },
    {
     "expr": "sum(rate(storj_sat_month_ingress{instance=~\"$node.*\"}[5m])) * 8",
     "legendFormat": "RateIn {{instance}}"
    },
    {
     "expr": "sum(storj_sat_month_egress{instance=~\"$node.*\"})",
     "legendFormat": "SumOut {{instance}}"
    },
    {
     "expr": "sum(storj_sat_month_ingress{instance=~\"$node.*\"})",
     "legendFormat": "SumIn {{instance}}"
    }
   ]
  },
  {
   "title": "$node Up to date",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "storj_upToDate_info{instance=~\"$node.*\"}",
     "legendFormat": "{{upToDate}}"
    }
   ]
  },
  {
   "title": "$node Vetting",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 25 },
   "targets": [
    {
     "expr": "storj_sat_audit{type=\"successCount\",instance=~\"$node.*\"}",
     "legendFormat": "{{satellite}}"
    }
   ]
  },
  {
   "title": "$node Storage In/Total",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes", "label": "Storage IO rate" }
   ],
   "targets": [
    {
     "expr": "delta(storj_total_diskspace{type=\"used\",instance=~\"$node.*\"}[5m]) * 8 / 300",
     "legendFormat": "DiskRate {{instance}}"
    },
    {
     "expr": "storj_total_diskspace{type=\"used\",instance=~\"$node.*\"}",
     "legendFormat": "DiskSum {{instance}}"
    }
   ]
  }
 ]
}